### ISSUE TITLE
ЗАЧЕТ

### ISSUE THREAD

**Issue by KipariS** [gingerrN/gingerrN.github.io#1]
Отличная работа. ДЗ№1
Особенно БЭМ-методология названия классов. 
Молодец.

**Comment by gingerrN** [comment]
Спасибо)))
Я конечно нашла у себя ошибку и попыталась исправить! Но у меня получилось
только на половину:
мой основной див не растягивается на полную высоту экрана, height:100% ;
min-height:100%  и height:auto не работают. С body - разобралась
И не получается сделать тень с двух сторон. Установила border слева и
справа.
Теперь я хочу обновить файлы, но гит баш не работает:
мой репозиторий на диске D
когда открываю гит баш и запрашую status, он мне выдает красным все папки,
которые лежат на диске С   - это первая проблема!
вторая:
ладно, в гит баше прохожу к своему репозиторию cd D:   , cd папка в которой
он лежит,...опять тут обновляю статус - говорит что какой-то из файлов был
изменен, но больше ничего,
делаю add .   - а он отвечает, что нечего добавлять, все без изменений!
мне нужно дойти именно до той папки, где лежат изначально эти измененные
файли и там сделать add . ?
короче, он работает как-то не правильно(

27 октября 2015 г., 13:57 пользователь Ivan <notifications@github.com>
написал:
